const CACHE='heartline-editor-3.9.0-editorial-pipeline';
const CORE=[
  './','./index.html','./heartline-app.css','./heartline-typography.css','./hl-editor/preview/presentation/preview-lab.css','./heartline-nav-fix.css','./heartline-reader-cleanup.css','./heartline-library-cards.css','./heartline-reader-hierarchy.css','./heartline-graph2.css',
  './heartline-app.js','./heartline-nav-fix.js','./heartline-project-stats.js','./heartline-graph.js','./heartline-graph-model.js','./heartline-graph-analysis.js','./heartline-graph-layout.js','./heartline-graph-layout-worker.js','./heartline-graph-renderers.js','./heartline-graph-navigation.js',
  './heartline-engine.js','./heartline-db.js','./heartline-domain.js','./heartline-assets.js','./heartline-image-worker.js','./heartline-player-renderer.js','./heartline-parser.js','./heartline-exporter.js',
  './hl-editor/index.js','./hl-editor/config.js','./hl-editor/domain/project.js','./hl-editor/domain/archive-policy.js','./hl-editor/application/project-service.js','./hl-editor/application/import-service.js','./hl-editor/ports/source-project-adapter.js','./hl-editor/ports/context-repository.js','./hl-editor/infrastructure/browser-hash-service.js','./hl-editor/infrastructure/browser-fs-source-adapter.js','./hl-editor/infrastructure/browser-context-repository.js','./hl-editor/presentation/bridge.js','./hl-editor/presentation/design-system.js','./hl-editor/presentation/design-system.css','./hl-editor/presentation/font-policy.js','./hl-editor/presentation/font-policy.css','./hl-editor/presentation/presentation-coordinator.js','./hl-editor/bootstrap/composition-root.js','./hl-editor/preview/domain/device-profile.js','./hl-editor/preview/application/device-profile-service.js','./hl-editor/preview/infrastructure/builtin-device-profile-catalog.js','./hl-editor/application/story-profile-runtime.js','./hl-editor/application/story-profile-registry.js','./hl-editor/application/source-adapter-registry.js','./hl-editor/application/legacy-editor-gateway.js','./hl-editor/application/asset-application-service.js','./hl-editor/application/sample-catalog-service.js','./hl-editor/application/service-container.js','./hl-editor/ports/story-format-profile.js','./hl-editor/ports/sample-catalog-repository.js','./hl-editor/infrastructure/story-profiles/generic-story-profile.js','./hl-editor/infrastructure/story-profiles/legacy-heartline-story-profile.js','./hl-editor/infrastructure/source-adapters/heartline-json-source-adapter.js','./hl-editor/infrastructure/source-adapters/heartline-json-source-policy.js','./hl-editor/infrastructure/browser-sample-catalog-repository.js','./samples/catalog.json',
  './hl-editor/editorial/domain/editorial-workflow.js','./hl-editor/editorial/application/editorial-workflow-service.js','./hl-editor/editorial/ports/editorial-workflow-repository.js','./hl-editor/editorial/ports/visual-asset-gateway.js','./hl-editor/editorial/infrastructure/browser-editorial-workflow-repository.js','./hl-editor/editorial/infrastructure/browser-visual-asset-gateway.js','./hl-editor/editorial/presentation/editorial-workspace.js','./hl-editor/editorial/presentation/editorial-workspace.css',
  './hl-editor/proofreading/domain/proofreading.js','./hl-editor/proofreading/application/proofreading-service.js','./hl-editor/proofreading/ports/proofreading-repository.js','./hl-editor/proofreading/infrastructure/browser-proofreading-repository.js','./hl-editor/proofreading/presentation/proofreading-workspace.js','./hl-editor/proofreading/presentation/proofreading.css',
  './novel.json','./moon-oath.json','./manifest.webmanifest','./icon-192.png','./icon-512.png'
];
self.addEventListener('install',event=>event.waitUntil(caches.open(CACHE).then(cache=>cache.addAll(CORE)).then(()=>self.skipWaiting())));
self.addEventListener('activate',event=>event.waitUntil(caches.keys().then(keys=>Promise.all(keys.filter(key=>key!==CACHE).map(key=>caches.delete(key)))).then(()=>self.clients.claim())));
self.addEventListener('fetch',event=>{if(event.request.method!=='GET')return;const url=new URL(event.request.url);if(url.origin!==location.origin)return;const nav=event.request.mode==='navigate';event.respondWith(fetch(event.request).then(response=>{if(response.ok)caches.open(CACHE).then(cache=>cache.put(event.request,response.clone()));return response}).catch(async()=>{const hit=await caches.match(event.request);if(hit)return hit;if(nav)return caches.match('./index.html');throw new Error('Offline resource unavailable')}))});
